"""Master Phishing Feature Extractor.

Unifies lexical, brand impersonation, DNS, and WHOIS feature extraction
into a clean, modular pipeline with pandas DataFrame and parallel batch support.
"""

from __future__ import annotations
from typing import Dict, Any, List
import pandas as pd
from tqdm import tqdm

from src.features.lexical import extract_lexical_features
from src.features.domain_brand import IndonesianBrandDetector
from src.features.dns_lookup import DNSFeatureExtractor
from src.features.whois_parser import WHOISFeatureExtractor


class PhishingFeatureExtractor:
    """End-to-end feature extraction pipeline for phishing URL classification."""

    def __init__(
        self,
        include_dns: bool = False,
        include_whois: bool = False,
        include_ngram_stacking: bool = False,
        brands_config_path=None,
    ):
        self.include_dns = include_dns
        self.include_whois = include_whois
        self.include_ngram_stacking = include_ngram_stacking

        self.brand_detector = (
            IndonesianBrandDetector(brands_config_path)
            if brands_config_path
            else IndonesianBrandDetector()
        )
        self.dns_extractor = DNSFeatureExtractor() if include_dns else None
        self.whois_extractor = WHOISFeatureExtractor() if include_whois else None
        self.ngram_stacker = None
        if include_ngram_stacking:
            from src.features.nlp_stacking import URLNgramStacker
            self.ngram_stacker = URLNgramStacker()

    def extract_single(self, url: str) -> Dict[str, Any]:
        """Extracts complete feature dictionary for a single URL."""
        features: Dict[str, Any] = {}

        # 1. Lexical & Structural Features
        lex_feats = extract_lexical_features(url)
        features.update(lex_feats)

        # 2. Indonesian Brand Impersonation & Typosquatting
        brand_feats = self.brand_detector.detect(url)
        features.update(brand_feats)

        # 3. DNS Features (if enabled)
        if self.include_dns and self.dns_extractor:
            dns_feats = self.dns_extractor.extract_from_live(url)
            features.update(dns_feats)

        # 4. WHOIS Features (if enabled)
        if self.include_whois and self.whois_extractor:
            whois_feats = self.whois_extractor.extract_from_live(url)
            features.update(whois_feats)

        return features

    def transform(
        self,
        df: pd.DataFrame,
        url_col: str = "url",
        show_progress: bool = True,
        y: Any | None = None,
    ) -> pd.DataFrame:
        """Transforms a DataFrame containing URLs into a feature matrix DataFrame."""
        if url_col not in df.columns:
            raise ValueError(f"Column '{url_col}' not found in DataFrame.")

        urls = df[url_col].tolist()
        iterator = tqdm(urls, desc="Extracting Features") if show_progress else urls

        records: List[Dict[str, Any]] = []
        for u in iterator:
            records.append(self.extract_single(u))

        feature_df = pd.DataFrame(records, index=df.index)

        # Optional N-Gram text stacking
        if self.include_ngram_stacking and self.ngram_stacker:
            if y is not None:
                ngram_df = self.ngram_stacker.fit_transform(urls, y)
            else:
                ngram_df = self.ngram_stacker.transform(urls)
            ngram_df.index = df.index
            feature_df = pd.concat([feature_df, ngram_df], axis=1)

        return feature_df

    def get_feature_names(self) -> List[str]:
        """Returns list of feature names generated by this extractor."""
        sample_url = "http://example.id"
        sample_dict = self.extract_single(sample_url)
        names = list(sample_dict.keys())
        if self.include_ngram_stacking:
            names.append("ngram_phish_prob")
        return names
